#ifndef MARATHONINTERFACE_GLOBAL_H
#define MARATHONINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MARATHONINTERFACE_LIBRARY)
#  define MARATHONINTERFACE_EXPORT Q_DECL_EXPORT
#else
#  define MARATHONINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // MARATHONINTERFACE_GLOBAL_H
